name: Run tests

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  all_features:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      name: Compile tests and examples on ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
        - run: cargo test --workspace --all-features --color=always
        - run: cargo build --workspace --all-features --examples

  rust_msrv:
    name: Check Rust MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.63.0"
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --workspace --all-features --color=always

  check_features:
    name: Check feature compilation matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --workspace --color=always --no-default-features
      - run: cargo test --workspace --color=always --no-default-features --features=alloc
      - run: cargo test --workspace --color=always --no-default-features --features=formatting
      - run: cargo test --workspace --color=always --no-default-features --features=parsing
      - run: cargo test --workspace --color=always --no-default-features --features=macros
